services:
  appointment-service:
    build:
      context: ./appointment-service
    container_name: appointment-service
    ports:
      - "8084:8084"
    environment:
      - DOCTOR_SERVICE_URL=http://doctor-service:8083

  doctor-service:
    build:
      context: ./doctor-service
    container_name: doctor-service
    ports:
      - "8083:8083"
    environment:
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8084
    depends_on:
      - appointment-service