# Replace with your actual SonarCloud project key and organization
sonar.projectKey=your-sonar-project-key
sonar.organization=your-sonar-organization

sonar.projectName=HospitalService
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/HospitalServiceApplication.java
