spring.application.name=doctor-service
server.port=8083

appointment.service.url=${APPOINTMENT_SERVICE_URL:https://appointment-service-hxup.onrender.com}
user.service.url=${USER_SERVICE_URL:https://healthcare-7pwe.onrender.com}
hospital.service.url=${HOSPITAL_SERVICE_URL:https://hospitalservice-633n.onrender.com}

spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:6543/postgres?user=postgres.fxxrtllzpzsktlftcwze&password=gDCeK8zfzRDbCZIb&prepareThreshold=0&preferQueryMode=simple
spring.datasource.username=postgres.fxxrtllzpzsktlftcwze
spring.datasource.password=gDCeK8zfzRDbCZIb
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.web.error.include-message=never
spring.web.error.include-binding-errors=never
spring.web.error.include-stacktrace=never
spring.web.error.include-exception=false

spring.mvc.log-request-details=false