sonar.projectKey=hiranoshadha_Test-HealthCare-appointment-service
sonar.organization=hiranoshadha

sonar.projectName=AppointmentService
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/AppointmentServiceApplication.java
