# Replace with your actual SonarCloud project key and organization
sonar.projectKey=hiranoshadha_Test-HealthCare
sonar.organization=hiranoshadha

sonar.projectName=HospitalService
sonar.projectVersion=0.0.1-SNAPSHOT

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.exclusions=**/UserServiceApplication.java
