spring.application.name=appointment-service
server.port=${PORT:8084}
doctor.service.url=${DOCTOR_SERVICE_URL:http://localhost:8083}

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.feqhigamnqiuolabebyg&password=postgres%401234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# HikariCP - fix connection timeout on Render free tier
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=60000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=30000