spring.application.name=appointment-service
server.port=8084
doctor.service.url=${DOCTOR_SERVICE_URL:http://localhost:8081}

spring.datasource.url=jdbc:postgresql://aws-1-ap-south-1.pooler.supabase.com:5432/postgres?user=postgres.feqhigamnqiuolabebyg&password=postgres@1234


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
